name: serverpod_architecture_shared
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Development707/Flutter-Serverpod-Architecture/serverpod_architecture_shared

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  serverpod_serialization: 2.0.0

dev_dependencies:
  build_runner: any
  freezed: any
  json_serializable: any
  lints: ^3.0.0
