name: serverpod_architecture_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://github.com/Development707/Flutter-Serverpod-Architecture
# repository: https://github.com/Development707/Flutter-Serverpod-Architecture/serverpod_architecture_server

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  serverpod: 2.0.0
  serverpod_serialization: 2.0.0
  serverpod_architecture_shared:
    path: ../serverpod_architecture_shared

dev_dependencies:
  lints: ^3.0.0
