name: serverpod_architecture_client
description: Starting point for a Serverpod client.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  serverpod_client: 1.2.6
  serverpod_architecture_shared:
    path: ../serverpod_architecture_shared
